# [Info]
site_name: 应用统计自学指南 # 左上角标题
site_url: https://XuankaiWang.github.io
site_author: kamdenwang
site_description: stats-self-learning
## [top-right corner]
repo_url: https://github.com/XuankaiWang/stats-self-learning # 右上角点击跳转的链接
repo_name: stats-self-learning # 右上角的名字



# [Navigtion] 左侧文章导航
nav:
  #- index.md
  - 前言: "index.md"
  - 如何使用这本书: "guide.md"
  - 仅供参考的学习路线: "path.md"
  - 实用工具:
    - 在线工具箱: "tool/online/index.md"
    - 编辑工具: "tool/edit/index.md"
    - 软件: "tool/software/index.md"
    - Mathematica: "tool/Mathematica/index.md"
    - ChatGPT: "tool/ChatGPT/index.md"
    - Docker: "tool/Docker/index.md"
    - Notion: "tool/Notion/index.md"
    - 发现与想象: "tool/imagine/index.md"
    - 日常学习工作流: "tool/study/index.md"

  - 数学分析(微积分):
    - "MIT 18.01/18.02: Calculus": "analysis/mit18.01.md"
  - 高等代数(线性代数):
    - "MIT 18.06: Linear Algebra": "algebra/mit18.06.md"
  - 初等数论:
    - "MIT 18.781: Theory Of Numbers": "number_theory/index.md"
  - 微分方程:
    - "MIT 18.03: Differential Equations": "ode/mit18.03.md"
    - "MIT RES.18-009: Learn Differential Equations: Up Close With Gilbert Strang And Cleve Moler": "ode/mit18.009.md" 
  - 矩阵(数值)分析:
    - "MIT 18.065: Matrix Methods In Data Analysis, Signal Processing, And Machine Learning": "矩阵数值分析/mit18.065.md"
    - "Stanford CS205A: Mathematical Methods for Computer Vision, Robotics, and Graphics": "矩阵数值分析/cs205a.md"
    - "WSU CSE559I: The art and science of positive definite matrices": "矩阵数值分析/cse559i.md"
    - "MIT 18.330 : Introduction to numerical analysis": "矩阵数值分析/mit18.330.md"
  - 概率论与随机过程:
    - "NTHU MATH2810: Probability": "probability/math2810.md"
    - "UCB CS126: Probability theory": "probability/UCB-CS126.md"
    - "Yale Statistics251/551: Stochastic Process": "probability/yale251.md"
  - 凸优化:
    - "Standford EE364A: Convex Optimization": "凸优化/convex.md"
  - 离散数学与应用概率论:
    - "UCB CS70: discrete Math and probability theory": "discrete_math/CS70.md"
  - 信息论相关: 
    - "MIT6.050J: Information theory and Entropy": "信息论相关/infomation_theory_and_entropy.md"
    - "The Information Theory, Pattern Recognition, and Neural Networks": "信息论相关/The_Information_Theory_Pattern_Recognition_and_Neural_Networks.md"
  - 数据科学:
    - "UCB Data100: Principles and Techniques of Data Science": "DS/Data100.md"
    - "UCB Data 8: Foundations of Data Science": "DS/Data8.md"



# [UI]
## [top]
theme:
  name: material
  palette:
    - scheme: default # 日间模式
      primary: deep blue # 上方的
      accent: blue # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: indigo
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式

  features:
    - header.autohide
    - navigation.tracking
    - #navigation.tabs # 使用Tab来进行分类
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - #navigation.path #
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - content.code.annotate
  language: zh # 一些提示性的文字会变成中文
  icon: # 'clound' 右上角图标的另一种样式，需要注释下行
    repo: fontawesome/brands/github
edit_uri: edit/main/docs # 编辑按钮跳转的链接

## [bottom-left corner]
copyright: © 2023 NWU-SoMer Copyright # 左下角的版权声明
## [bottom-right corner]
extra:
  social: # icons
    - icon: fontawesome/brands/docker
      link: https://starryious.github.io/KamdenWang2003.github.io/
      name: Website | XuankaiWang
    - icon: fontawesome/brands/github
      link: https://github.com/XuankaiWang/stats-self-learning
      name: GitHub | stats-self-learning
    

# [Extensions]
plugins:
  - search: # 现在还不支持中文搜索 支持之后可以设置语言
    # insider已经支持中文的分词搜索了 https://squidfunk.github.io/mkdocs-material/blog/2022/chinese-search-support/
      lang:
        - en
        - ja
      enable_anchors: true
  - tags # 给单篇文章添加标签 https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/?h=tags
markdown_extensions:
  - pymdownx.arithmatex: # latex支持
      generic: true
  - attr_list # 给图片后面添加{width="300"}设置大小
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      linenums: true # 显示行号
      auto_title: true # 显示编程语言名称
  - pymdownx.superfences # 代码块高亮插件
  - meta # 支持Markdown文件上方自定义标题标签等
  - admonition # https://squidfunk.github.io/mkdocs-material/reference/admonitions/#inline-blocks
  - pymdownx.details # admonition需要
  - attr_list
  - md_in_html


extra_javascript:
  # latex支持
  # check https://squidfunk.github.io/mkdocs-material/reference/mathjax/?h=math for more information
  # notice `curl https://polyfill.io/v3/polyfill.min.js?features=es6 > docs/mkdocs/javascripts/polyfill.min.js && curl https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js > docs/mkdocs/javascripts/tex-mml-chtml.js` not works... because there are other resources that need to load
  - attach/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js # https://cdn.bytedance.com/?query=mathjax&version=3.2.0
  
extra_css:
  # - attach/css/no-footer.css # 不使用底部的翻页
  - attach/css/unordered-list-symbols.css # multiplt unordered list symbols

google_analytics: 
  - 'UA-35232574'
  - 'auto'

# Lastly Update by Xuankai Wang in 2023/04/05.
